export type LocalizedString = { ka: string; en: string };

export const copy = {
  nav: {
    signIn: { ka: "შესვლა", en: "Sign in" },
    openApp: { ka: "აპის გახსნა", en: "Open app" },
  },
  hero: {
    title: {
      ka: "შენი ნახაზი და დიზაინი უკვე აეწყო",
      en: "Your drawings and design — already assembled",
    },
    sub: {
      ka: "დიზაინი კლიენტის ნამდვილ კედელზე ჩნდება კონსულტაციის დროსვე, ზუსტი ნახაზები კი მზადაა საათებში — და არა კვირებში.",
      en: "The design appears on the client's real wall during the consultation — and precise drawings are ready in hours, not weeks.",
    },
    cta: { ka: "დაიწყე პროექტი", en: "Start a project" },
    secondary: { ka: "როგორ მუშაობს", en: "How it works" },
  },
  how: {
    title: { ka: "როგორ მუშაობს", en: "How it works" },
    steps: [
      {
        num: "01",
        title: { ka: "დიზაინი", en: "Design" },
        body: {
          ka: "AI ავეჯს კლიენტის ნამდვილი კედლის ფოტოზე გამოსახავს — პირდაპირ კონსულტაციაზე.",
          en: "AI renders the furniture on the client's real wall photo — live at the consultation.",
        },
      },
      {
        num: "02",
        title: { ka: "ზომები", en: "Measurements" },
        body: {
          ka: "პარტნიორი ადგილზე იღებს ზუსტ ზომებს იმავე პროექტში.",
          en: "The partner takes exact site measurements into the same project.",
        },
      },
      {
        num: "03",
        title: { ka: "ნახაზი", en: "Drawings" },
        body: {
          ka: "ძრავი ქმნის უზადო, დაზომილ ნახაზებს და საჭრელ სიებს — იმავე დღეს.",
          en: "The engine produces flawless dimensioned drawings and cut lists — the same day.",
        },
      },
    ],
  },
  why: {
    title: { ka: "რატომ aewyo", en: "Why aewyo" },
    values: [
      {
        title: { ka: "საათები და არა კვირები", en: "Hours, not weeks" },
        body: {
          ka: "რენდერი კონსულტაციაზე, ნახაზი იმავე დღეს.",
          en: "A render at the consultation, drawings the same day.",
        },
      },
      {
        title: { ka: "მილიმეტრული სიზუსტე", en: "Millimeter precision" },
        body: {
          ka: "დეტერმინისტული ძრავი — არანაირი ვარაუდი.",
          en: "A deterministic engine — no guesswork.",
        },
      },
      {
        title: {
          ka: "დამზადებულია ხელოსნების მიერ",
          en: "Built by woodworkers",
        },
        body: {
          ka: "წესები სახელოსნოდან მოდის და არა ქაღალდიდან.",
          en: "The rules come from the workshop floor, not from paper.",
        },
      },
    ],
  },
  band: {
    line: {
      ka: "მზად ხარ? პირველი ნახაზი დღესვე.",
      en: "Ready? Your first drawing today.",
    },
    cta: { ka: "დაიწყე პროექტი", en: "Start a project" },
  },
  appStub: {
    line: {
      ka: "სამუშაო სივრცე მალე გაიხსნება.",
      en: "The workspace opens soon.",
    },
    back: { ka: "მთავარ გვერდზე დაბრუნება", en: "Back to the home page" },
  },
  studio: {
    title: { ka: "სტუდია", en: "Studio" },
    params: { ka: "პარამეტრები", en: "Parameters" },
    fields: {
      width: { ka: "სიგანე", en: "Width" },
      height: { ka: "სიმაღლე", en: "Height" },
      depth: { ka: "სიღრმე", en: "Depth" },
      thickness: { ka: "მასალის სისქე", en: "Material thickness" },
      backThickness: { ka: "ზურგის სისქე", en: "Back thickness" },
      shelfCount: { ka: "თაროების რაოდენობა", en: "Shelves" },
      plinthHeight: { ka: "ცოკოლის სიმაღლე", en: "Plinth height" },
      shelfSetback: { ka: "თაროს უკუწევა", en: "Shelf setback" },
    },
    drawing: { ka: "ნახაზი", en: "Drawing" },
    cutList: { ka: "საჭრელი სია", en: "Cut list" },
    table: {
      part: { ka: "დეტალი", en: "Part" },
      qty: { ka: "რაოდ.", en: "Qty" },
      length: { ka: "სიგრძე", en: "Length" },
      width: { ka: "სიგანე", en: "Width" },
      thickness: { ka: "სისქე", en: "Thickness" },
    },
    parts: {
      side: { ka: "გვერდი", en: "Side" },
      top: { ka: "ზედა პანელი", en: "Top" },
      bottom: { ka: "ძირი", en: "Bottom" },
      shelf: { ka: "თარო", en: "Shelf" },
      back: { ka: "ზურგი", en: "Back" },
      plinth: { ka: "ცოკოლი", en: "Plinth" },
      door: { ka: "კარი", en: "Door" },
      drawerFront: { ka: "უჯრის ფასადი", en: "Drawer front" },
      drawerSide: { ka: "უჯრის გვერდი", en: "Drawer side" },
      drawerRail: { ka: "უჯრის კედელი", en: "Drawer rail" },
      drawerBottom: { ka: "უჯრის ძირი", en: "Drawer bottom" },
      blindPanel: { ka: "ბრმა ფასადი", en: "Blind panel" },
    },
    front: {
      label: { ka: "ფასადი", en: "Front" },
      none: { ka: "ღია", en: "Open" },
      doors: { ka: "კარები", en: "Doors" },
      drawers: { ka: "უჯრები", en: "Drawers" },
      doorCount: { ka: "კარების რაოდენობა", en: "Doors" },
      drawerCount: { ka: "უჯრების რაოდენობა", en: "Drawers" },
      reveal: { ka: "ღრეჩო", en: "Reveal" },
      carcassDecor: { ka: "კორპუსის დეკორი", en: "Carcass decor" },
      frontDecor: { ka: "ფასადის დეკორი", en: "Front decor" },
    },
    hardware: {
      title: { ka: "ფურნიტურა", en: "Hardware" },
      hinge: { ka: "ანჯამა", en: "Hinge" },
      slidePair: { ka: "მიმმართველი (წყვილი)", en: "Slide pair" },
    },
    decorColumn: { ka: "დეკორი", en: "Decor" },
    kitchen: {
      walls: { ka: "კედლები", en: "Walls" },
      wall: { ka: "კედელი", en: "Wall" },
      length: { ka: "სიგრძე", en: "Length" },
      wallHeight: { ka: "კედლის სიმაღლე", en: "Wall height" },
      bandHeight: {
        ka: "ზედაპირიდან საკიდებამდე",
        en: "Counter to wall units",
      },
      cabinets: { ka: "კარადები", en: "Cabinets" },
      presets: {
        baseDoors: { ka: "ქვედა · კარები", en: "Base · doors" },
        baseDrawers: { ka: "ქვედა · უჯრები", en: "Base · drawers" },
        sink: { ka: "ნიჟარა", en: "Sink" },
        oven: { ka: "ღუმელი", en: "Oven" },
        hob: { ka: "ქურა", en: "Hob" },
        fridge: { ka: "მაცივარი", en: "Fridge" },
        hood: { ka: "გამწოვი", en: "Hood" },
        wallUnit: { ka: "საკიდი", en: "Wall unit" },
        tallUnit: { ka: "მაღალი", en: "Tall unit" },
        space: { ka: "ღია სივრცე", en: "Space" },
      },
      duplicate: { ka: "დუბლირება", en: "Duplicate" },
      pdf: { ka: "PDF", en: "PDF" },
      exportPdf: { ka: "PDF ექსპორტი", en: "Export as PDF" },
      generatingPdf: { ka: "მზადდება PDF…", en: "Generating PDF…" },
      layout: { ka: "გეგმარება", en: "Layout" },
      layoutTitle: { ka: "გეგმარება და ნახაზები", en: "Layout & Drawings" },
      layoutSubtitle: {
        ka: "2D ნახაზები, კედლის ხედები და საჭრელი სიები",
        en: "2D drawings, wall elevations, and cut lists",
      },
      collapseSidebar: { ka: "პანელის ჩაკეცვა", en: "Collapse sidebar" },
      expandSidebar: { ka: "პანელის გახსნა", en: "Expand sidebar" },
      allViews: { ka: "ყველა", en: "All" },
      planAndElevations: { ka: "გეგმა და ხედები", en: "Plan & Elevations" },
      print: { ka: "ბეჭდვა · PDF-ად შენახვა", en: "Print · Save as PDF" },
      packet: { ka: "სახელოსნო პაკეტი", en: "Workshop packet" },
      backToStudio: { ka: "სტუდიაში დაბრუნება", en: "Back to the studio" },
      summary: { ka: "შემადგენლობა", en: "Contents" },
      pdfReady: { ka: "PDF გადმოწერილია", en: "PDF downloaded" },
      pdfFailed: { ka: "PDF ვერ შეიქმნა", en: "PDF export failed" },
      pdfPage: { ka: "გვერდი", en: "Page" },
      band: { ka: "რიგი", en: "Band" },
      bandBase: { ka: "ქვედა", en: "Base" },
      bandWall: { ka: "საკიდი", en: "Wall" },
      bandTall: { ka: "მაღალი", en: "Tall" },
      spacer: { ka: "ღია სივრცე", en: "Space" },
      appliance: { ka: "ტექნიკა", en: "Appliance" },
      date: { ka: "თარიღი", en: "Date" },
      // projects
      projects: { ka: "პროექტები", en: "Projects" },
      newProject: { ka: "ახალი პროექტი", en: "New project" },
      untitled: { ka: "სამზარეულო", en: "Kitchen" },
      save: { ka: "შენახვა", en: "Save" },
      unsaved: { ka: "შეუნახავი ცვლილებები", en: "Unsaved changes" },
      savedAt: { ka: "შენახულია", en: "Saved" },
      neverSaved: { ka: "ჯერ არ შენახულა", en: "Not saved yet" },
      deleteProject: { ka: "პროექტის წაშლა", en: "Delete project" },
      confirmDelete: {
        ka: "წავშალოთ ეს პროექტი? ამის გაუქმება შეუძლებელია.",
        en: "Delete this project? This cannot be undone.",
      },
      confirmDiscard: {
        ka: "შეუნახავი ცვლილებები დაიკარგება. გავაგრძელოთ?",
        en: "Unsaved changes will be lost. Continue?",
      },
      projectName: { ka: "პროექტის სახელი", en: "Project name" },
      open: { ka: "გახსნა", en: "Open" },
      signInToSave: {
        ka: "შესანახად გაიარე ავტორიზაცია",
        en: "Sign in to save projects",
      },
      // editing
      undo: { ka: "დაბრუნება", en: "Undo" },
      redo: { ka: "გამეორება", en: "Redo" },
      shortcuts: { ka: "მალსახმობები", en: "Shortcuts" },
      shortcutList: {
        ka: "Ctrl+S შენახვა · Ctrl+Z / Ctrl+Y დაბრუნება · Ctrl+C / Ctrl+V კოპირება · Ctrl+D დუბლირება · Delete წაშლა · Esc დახურვა",
        en: "Ctrl+S save · Ctrl+Z / Ctrl+Y undo · Ctrl+C / Ctrl+V copy · Ctrl+D duplicate · Delete remove · Esc close",
      },
      loading: { ka: "იტვირთება…", en: "Loading…" },
      // walls step
      stepWalls: { ka: "კედლები", en: "Walls" },
      stepCabinets: { ka: "კარადები", en: "Cabinets" },
      wallsIntro: {
        ka: "ჯერ ააწყვე ოთახი: კედლების სიგრძე და მოხვევის მიმართულება. ნიშა = გარეთ, შიგნით, შიგნით, გარეთ.",
        en: "Build the room first: wall lengths and the turn at each joint. A niche = out, in, in, out.",
      },
      wallsDone: { ka: "მზადაა → კარადები", en: "Done → cabinets" },
      addWall: { ka: "კედლის დამატება", en: "Add wall" },
      insertWallAfter: { ka: "კედლის ჩამატება შემდეგ", en: "Insert wall after" },
      removeWall: { ka: "კედლის წაშლა", en: "Remove wall" },
      turnRight: { ka: "შიდა კუთხე", en: "Inside corner" },
      turnLeft: { ka: "გარე კუთხე", en: "Outside corner" },
      turn: { ka: "მოხვევა", en: "Turn" },
      // corners
      corner: { ka: "კუთხე", en: "Corner" },
      cornerBase: { ka: "კუთხის კარადა", en: "Corner cabinet" },
      cornerWall: { ka: "კუთხის საკიდი", en: "Corner wall unit" },
      cornerAt: { ka: "კუთხე", en: "Corner" },
      legA: { ka: "მხარი კედლის გასწვრივ", en: "Leg along wall" },
      legB: { ka: "მხარი კედლის გასწვრივ", en: "Leg along wall" },
      cornerStyle: { ka: "ტიპი", en: "Style" },
      diagonal: { ka: "დიაგონალური", en: "Diagonal" },
      blind: { ka: "ბრმა", en: "Blind" },
      cornerNeedsInside: {
        ka: "კუთხის კარადა მხოლოდ შიდა კუთხეზე დგება",
        en: "Corner cabinets go on inside corners only",
      },
      // 3D view
      viewIso: { ka: "იზო", en: "Iso" },
      viewPersp: { ka: "პერსპექტივა", en: "Perspective" },
      // pdf cover
      materials: { ka: "მასალები", en: "Material palette" },
      overview: { ka: "მიმოხილვა", en: "Overview" },
      total: { ka: "სულ", en: "Total" },
      navHint: {
        ka: "Space + გადათრევა — კარადის გადატანა · Alt + გადათრევა — ბრუნვა · მარჯვენა — პანორამა · სქროლი — ზუმი",
        en: "Space + drag — move cabinet · Alt + drag — orbit · right drag — pan · scroll — zoom",
      },
      free: { ka: "თავისუფალია", en: "free" },
      plan: { ka: "გეგმა", en: "Plan" },
      elevations: { ka: "კედლის ხედები", en: "Wall elevations" },
      fullCutList: { ka: "სრული საჭრელი სია", en: "Full cut list" },
      card: { ka: "ასაწყობი ბარათი", en: "Assembly card" },
      remove: { ka: "წაშლა", en: "Remove" },
      saved: { ka: "შენახულია", en: "Saved" },
      saving: { ka: "ინახება…", en: "Saving…" },
      selectHint: {
        ka: "აირჩიე კარადა გეგმაზე ან სიაში",
        en: "Select a cabinet on the plan or in the list",
      },
    },
  },
} as const;
